spring:
  datasource:
    url: jdbc:mysql://localhost:3306/transportador?serverTimezone=UTC
    username: root
    password: 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
