spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fornecedor
    username: root
    password: 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
