spring: 
  datasource:
    password:
    url: "jdbc:mysql://localhost:3306/fornecedor"
    username: root
  jpa: 
    hibernate: 
      ddl-auto: create
    properties: 
      hibernate: 
        jdbc: 
          time_zone: UTC
    show-sql: true
      
